-- fix_passwords.sql
-- Fix SHA-256 password hashes to bcrypt for auth service compatibility.
-- Also ensures test accounts (from README.md + link_test_accounts.sql) exist.

\set ON_ERROR_STOP on

-- bcrypt hash of "password123" (generated by Go's bcrypt)
-- Use this value directly in SQL string literals:
-- '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm'

-- 1. Fix all UMKM/MITRA password hashes to bcrypt
UPDATE auth.master_akunpengguna
SET password_hash = '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm',
    status_aktif = TRUE
WHERE peran_id IN ('UMKM', 'MITRA');

-- 2. Update registrasi status to APPROVED for all UMKM/MITRA
UPDATE user_mgmt.transaksi_registrasipengguna r
SET status_verifikasi_id = 'DISETUJUI'
FROM auth.master_akunpengguna a
WHERE r.akun_id = a.akun_id
  AND a.peran_id IN ('UMKM', 'MITRA');

-- 3. Create test accounts with upsert (handle email + no_hp conflicts)
DO $$
BEGIN
  -- admin account
  INSERT INTO auth.master_akunpengguna (akun_id, peran_id, nama_lengkap, email, no_hp, password_hash, status_aktif, created_at, updated_at)
  VALUES ('AKUNADMIN001', 'ADMIN', 'Admin Pemerintah', 'admin@example.com', '999000000001',
          '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', TRUE, NOW(), NOW())
  ON CONFLICT (email) DO UPDATE SET password_hash = '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', status_aktif = TRUE;

  -- admin record in master_admin
  INSERT INTO auth.master_admin (admin_id, akun_id, kode_admin, is_active, created_at, updated_at)
  SELECT 'ADM-TEST-001', akun_id, 'ADM001', 'active', NOW(), NOW()
  FROM auth.master_akunpengguna WHERE email = 'admin@example.com'
  ON CONFLICT (akun_id) DO NOTHING;

  -- README UMKM
  INSERT INTO auth.master_akunpengguna (akun_id, peran_id, nama_lengkap, email, no_hp, password_hash, status_aktif, created_at, updated_at)
  VALUES ('AKUN-README-UMKM', 'UMKM', 'Reza Wahyuni', 'rezawahyuni525@umkm.id', '999000000002',
          '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', TRUE, NOW(), NOW())
  ON CONFLICT (email) DO UPDATE SET password_hash = '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', status_aktif = TRUE;

  -- README MITRA
  INSERT INTO auth.master_akunpengguna (akun_id, peran_id, nama_lengkap, email, no_hp, password_hash, status_aktif, created_at, updated_at)
  VALUES ('AKUN-README-MITRA', 'MITRA', 'Fauzan Kusuma', 'fauzan.kusuma54@mitra.id', '999000000003',
          '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', TRUE, NOW(), NOW())
  ON CONFLICT (email) DO UPDATE SET password_hash = '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', status_aktif = TRUE;

  -- TEST UMKM
  INSERT INTO auth.master_akunpengguna (akun_id, peran_id, nama_lengkap, email, no_hp, password_hash, status_aktif, created_at, updated_at)
  VALUES ('AKUN-TEST-UMKM', 'UMKM', 'UMKM Test', 'umkm@test.com', '999000000004',
          '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', TRUE, NOW(), NOW())
  ON CONFLICT (email) DO UPDATE SET password_hash = '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', status_aktif = TRUE;

  -- TEST MITRA
  INSERT INTO auth.master_akunpengguna (akun_id, peran_id, nama_lengkap, email, no_hp, password_hash, status_aktif, created_at, updated_at)
  VALUES ('AKUN-TEST-MITRA', 'MITRA', 'Mitra Test', 'mitra@test.com', '999000000005',
          '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', TRUE, NOW(), NOW())
  ON CONFLICT (email) DO UPDATE SET password_hash = '$2a$10$i4zh4ChkGz83OiOUXt65mOYPYg8GdcLWM9TBW9evmAqXSGcGf6kpm', status_aktif = TRUE;
END $$;

-- 6. Create transaksi_registrasipengguna records for test accounts (so status = DISETUJUI, not MENUNGGU)
-- Look up akun_id by email (accounts may already exist in CSV with different akun_id)
DO $$
DECLARE
  v_akun_id TEXT;
BEGIN
  -- Admin
  SELECT akun_id INTO v_akun_id FROM auth.master_akunpengguna WHERE email = 'admin@example.com';
  IF v_akun_id IS NOT NULL THEN
    INSERT INTO user_mgmt.transaksi_registrasipengguna (akun_id, status_verifikasi_id, kode_registrasi, tanggal_submit, checklist_informasi_lengkap)
    VALUES (v_akun_id, 'DISETUJUI', 'REG-ADMIN', NOW(), TRUE)
    ON CONFLICT (akun_id) DO NOTHING;
  END IF;

  -- README UMKM
  SELECT akun_id INTO v_akun_id FROM auth.master_akunpengguna WHERE email = 'rezawahyuni525@umkm.id';
  IF v_akun_id IS NOT NULL THEN
    INSERT INTO user_mgmt.transaksi_registrasipengguna (akun_id, status_verifikasi_id, kode_registrasi, tanggal_submit, checklist_informasi_lengkap)
    VALUES (v_akun_id, 'DISETUJUI', 'REG-README-UMKM', NOW(), TRUE)
    ON CONFLICT (akun_id) DO NOTHING;
  END IF;

  -- README MITRA
  SELECT akun_id INTO v_akun_id FROM auth.master_akunpengguna WHERE email = 'fauzan.kusuma54@mitra.id';
  IF v_akun_id IS NOT NULL THEN
    INSERT INTO user_mgmt.transaksi_registrasipengguna (akun_id, status_verifikasi_id, kode_registrasi, tanggal_submit, checklist_informasi_lengkap)
    VALUES (v_akun_id, 'DISETUJUI', 'REG-README-MITRA', NOW(), TRUE)
    ON CONFLICT (akun_id) DO NOTHING;
  END IF;

  -- TEST UMKM
  SELECT akun_id INTO v_akun_id FROM auth.master_akunpengguna WHERE email = 'umkm@test.com';
  IF v_akun_id IS NOT NULL THEN
    INSERT INTO user_mgmt.transaksi_registrasipengguna (akun_id, status_verifikasi_id, kode_registrasi, tanggal_submit, checklist_informasi_lengkap)
    VALUES (v_akun_id, 'DISETUJUI', 'REG-TEST-UMKM', NOW(), TRUE)
    ON CONFLICT (akun_id) DO NOTHING;
  END IF;

  -- TEST MITRA
  SELECT akun_id INTO v_akun_id FROM auth.master_akunpengguna WHERE email = 'mitra@test.com';
  IF v_akun_id IS NOT NULL THEN
    INSERT INTO user_mgmt.transaksi_registrasipengguna (akun_id, status_verifikasi_id, kode_registrasi, tanggal_submit, checklist_informasi_lengkap)
    VALUES (v_akun_id, 'DISETUJUI', 'REG-TEST-MITRA', NOW(), TRUE)
    ON CONFLICT (akun_id) DO NOTHING;
  END IF;
END $$;

\echo 'Password fix complete. All accounts use bcrypt(password123).'
