-- Load UMKM Tumbuh schema-first generated CSV data.
-- Run from /app/data where csv/*.csv exists.
-- Intended for infra/db/dummy/seed-csv generated by generate_umkm_tumbuh_schema_first.py.
\set ON_ERROR_STOP on

-- =============================================================================
-- REFERENCE TABLES
-- =============================================================================

-- The schema migrations may already seed reference rows. For schema-first dummy loading,
-- make this loader own the reference IDs from csv/ref_*.csv so FK values generated
-- by the dummy generator cannot collide with pre-seeded lookup names.
-- Intended for clean/dev dummy seed runs. CASCADE will remove existing dependent dummy data.
TRUNCATE TABLE
  ref.ref_dimwaktu,
  ref.ref_jenisdokumen,
  ref.ref_statusdokumen,
  ref.ref_statusverifikasi,
  ref.ref_statusperkembangan,
  ref.ref_statuspengajuan,
  ref.ref_statussertifikat,
  ref.ref_statussubmission,
  ref.ref_statuspendaftaranpelatihan,
  ref.ref_statuspelatihan,
  ref.ref_jenispelatihan,
  ref.ref_statusmitra,
  ref.ref_statusumkm,
  ref.ref_skalakerjasama,
  ref.ref_bentukdukungan,
  ref.ref_bidangkemitraan,
  ref.ref_jenismitra,
  ref.ref_jenisumkm,
  ref.ref_kategoriproduk,
  ref.ref_kategoriusaha,
  ref.ref_skalausaha,
  ref.ref_peranpengguna
RESTART IDENTITY CASCADE;
CREATE TEMP TABLE _r (id VARCHAR(30), name VARCHAR(200));

\copy _r FROM 'csv/ref_skalausaha.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_skalausaha (skala_usaha_id, nama_skala_usaha)
SELECT id, name FROM _r
ON CONFLICT (skala_usaha_id) DO UPDATE SET nama_skala_usaha = EXCLUDED.nama_skala_usaha;
TRUNCATE _r;

\copy _r FROM 'csv/ref_kategoriusaha.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_kategoriusaha (kategori_usaha_id, nama_kategori_usaha)
SELECT id, name FROM _r
ON CONFLICT (kategori_usaha_id) DO UPDATE SET nama_kategori_usaha = EXCLUDED.nama_kategori_usaha;
TRUNCATE _r;

\copy _r FROM 'csv/ref_kategoriproduk.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_kategoriproduk (kategori_produk_id, nama_kategori_produk)
SELECT id, name FROM _r
ON CONFLICT (kategori_produk_id) DO UPDATE SET nama_kategori_produk = EXCLUDED.nama_kategori_produk;
TRUNCATE _r;

\copy _r FROM 'csv/ref_jenisumkm.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_jenisumkm (jenis_umkm_id, nama_jenis_umkm)
SELECT id, name FROM _r
ON CONFLICT (jenis_umkm_id) DO UPDATE SET nama_jenis_umkm = EXCLUDED.nama_jenis_umkm;
TRUNCATE _r;

\copy _r FROM 'csv/ref_jenismitra.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_jenismitra (jenis_mitra_id, nama_jenis_mitra)
SELECT id, name FROM _r
ON CONFLICT (jenis_mitra_id) DO UPDATE SET nama_jenis_mitra = EXCLUDED.nama_jenis_mitra;
TRUNCATE _r;

\copy _r FROM 'csv/ref_bidangkemitraan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_bidangkemitraan (bidang_kemitraan_id, nama_bidang_kemitraan)
SELECT id, name FROM _r
ON CONFLICT (bidang_kemitraan_id) DO UPDATE SET nama_bidang_kemitraan = EXCLUDED.nama_bidang_kemitraan;
TRUNCATE _r;

\copy _r FROM 'csv/ref_bentukdukungan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_bentukdukungan (bentuk_dukungan_id, nama_bentuk_dukungan)
SELECT id, name FROM _r
ON CONFLICT (bentuk_dukungan_id) DO UPDATE SET nama_bentuk_dukungan = EXCLUDED.nama_bentuk_dukungan;
TRUNCATE _r;

\copy _r FROM 'csv/ref_skalakerjasama.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_skalakerjasama (skala_kerjasama_id, nama_skala_kerjasama)
SELECT id, name FROM _r
ON CONFLICT (skala_kerjasama_id) DO UPDATE SET nama_skala_kerjasama = EXCLUDED.nama_skala_kerjasama;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statusumkm.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statusumkm (status_umkm_id, nama_status_umkm)
SELECT id, name FROM _r
ON CONFLICT (status_umkm_id) DO UPDATE SET nama_status_umkm = EXCLUDED.nama_status_umkm;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statusmitra.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statusmitra (status_mitra_id, nama_status_mitra)
SELECT id, name FROM _r
ON CONFLICT (status_mitra_id) DO UPDATE SET nama_status_mitra = EXCLUDED.nama_status_mitra;
TRUNCATE _r;

\copy _r FROM 'csv/ref_jenispelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_jenispelatihan (jenis_pelatihan_id, nama_jenis_pelatihan)
SELECT id, name FROM _r
ON CONFLICT (jenis_pelatihan_id) DO UPDATE SET nama_jenis_pelatihan = EXCLUDED.nama_jenis_pelatihan;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statuspelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statuspelatihan (status_pelatihan_id, nama_status_pelatihan)
SELECT id, name FROM _r
ON CONFLICT (status_pelatihan_id) DO UPDATE SET nama_status_pelatihan = EXCLUDED.nama_status_pelatihan;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statuspendaftaranpelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statuspendaftaranpelatihan (status_pendaftaran_pelatihan_id, nama_status_pendaftaran)
SELECT id, name FROM _r
ON CONFLICT (status_pendaftaran_pelatihan_id) DO UPDATE SET nama_status_pendaftaran = EXCLUDED.nama_status_pendaftaran;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statussubmission.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statussubmission (status_submission_id, nama_status_submission)
SELECT id, name FROM _r
ON CONFLICT (status_submission_id) DO UPDATE SET nama_status_submission = EXCLUDED.nama_status_submission;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statussertifikat.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statussertifikat (status_sertifikat_id, nama_status_sertifikat)
SELECT id, name FROM _r
ON CONFLICT (status_sertifikat_id) DO UPDATE SET nama_status_sertifikat = EXCLUDED.nama_status_sertifikat;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statuspengajuan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statuspengajuan (status_pengajuan_id, nama_status_pengajuan)
SELECT id, name FROM _r
ON CONFLICT (status_pengajuan_id) DO UPDATE SET nama_status_pengajuan = EXCLUDED.nama_status_pengajuan;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statusperkembangan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statusperkembangan (status_perkembangan_id, nama_status_perkembangan)
SELECT id, name FROM _r
ON CONFLICT (status_perkembangan_id) DO UPDATE SET nama_status_perkembangan = EXCLUDED.nama_status_perkembangan;
TRUNCATE _r;

\copy _r FROM 'csv/ref_statusdokumen.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statusdokumen (status_dokumen_id, nama_status_dokumen)
SELECT id, name FROM _r
ON CONFLICT (status_dokumen_id) DO UPDATE SET nama_status_dokumen = EXCLUDED.nama_status_dokumen;
TRUNCATE _r;

\copy _r FROM 'csv/ref_peranpengguna.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_peranpengguna (peran_id, nama_peran)
SELECT id, name FROM _r
ON CONFLICT (peran_id) DO UPDATE SET nama_peran = EXCLUDED.nama_peran;
DROP TABLE _r;

CREATE TEMP TABLE _r3 (id VARCHAR(30), name VARCHAR(100));
\copy _r3 FROM 'csv/ref_statusverifikasi.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_statusverifikasi (status_verifikasi_id, nama_status_verifikasi)
SELECT id, name FROM _r3
ON CONFLICT (status_verifikasi_id) DO UPDATE SET nama_status_verifikasi = EXCLUDED.nama_status_verifikasi;
DROP TABLE _r3;

CREATE TEMP TABLE _rd AS SELECT
  jenis_dokumen_id,
  nama_jenis_dokumen,
  deskripsi,
  allowed_extensions,
  max_size_mb,
  wajib_umkm,
  wajib_mitra,
  wajib_pengajuan_kemitraan
FROM ref.ref_jenisdokumen WHERE false;
\copy _rd FROM 'csv/ref_jenisdokumen.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_jenisdokumen (
  jenis_dokumen_id, nama_jenis_dokumen, deskripsi, allowed_extensions,
  max_size_mb, wajib_umkm, wajib_mitra, wajib_pengajuan_kemitraan
)
SELECT * FROM _rd
ON CONFLICT (jenis_dokumen_id) DO UPDATE SET
  nama_jenis_dokumen = EXCLUDED.nama_jenis_dokumen,
  deskripsi = EXCLUDED.deskripsi,
  allowed_extensions = EXCLUDED.allowed_extensions,
  max_size_mb = EXCLUDED.max_size_mb,
  wajib_umkm = EXCLUDED.wajib_umkm,
  wajib_mitra = EXCLUDED.wajib_mitra,
  wajib_pengajuan_kemitraan = EXCLUDED.wajib_pengajuan_kemitraan;
DROP TABLE _rd;

CREATE TEMP TABLE _dw AS SELECT
  tanggal,
  hari,
  minggu_ke,
  minggu_bulan,
  tanggal_awal_minggu,
  tanggal_akhir_minggu,
  bulan,
  nama_bulan,
  kuartal,
  tahun,
  is_weekend
FROM ref.ref_dimwaktu WHERE false;
\copy _dw FROM 'csv/ref_dimwaktu.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO ref.ref_dimwaktu (
  tanggal, hari, minggu_ke, minggu_bulan, tanggal_awal_minggu,
  tanggal_akhir_minggu, bulan, nama_bulan, kuartal, tahun, is_weekend
)
SELECT * FROM _dw
ON CONFLICT (tanggal) DO NOTHING;
DROP TABLE _dw;

-- =============================================================================
-- MASTER TABLES
-- =============================================================================
CREATE TEMP TABLE _a AS SELECT
  akun_id,
  peran_id,
  nama_lengkap,
  email,
  no_hp,
  password_hash,
  status_aktif,
  email_verified_at,
  last_login_at,
  created_at,
  updated_at
FROM auth.master_akunpengguna WHERE false;
\copy _a FROM 'csv/master_akunpengguna.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO auth.master_akunpengguna (
  akun_id, peran_id, nama_lengkap, email, no_hp, password_hash,
  status_aktif, email_verified_at, last_login_at, created_at, updated_at
)
SELECT * FROM _a
ON CONFLICT (akun_id) DO NOTHING;
DROP TABLE _a;

CREATE TEMP TABLE _adm AS SELECT
  admin_id,
  akun_id,
  kode_admin,
  is_active,
  created_at,
  updated_at
FROM auth.master_admin WHERE false;
\copy _adm FROM 'csv/master_admin.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO auth.master_admin (admin_id, akun_id, kode_admin, is_active, created_at, updated_at)
SELECT * FROM _adm
ON CONFLICT (admin_id) DO NOTHING;
DROP TABLE _adm;

CREATE TEMP TABLE _lok AS SELECT
  lokasi_id,
  provinsi,
  kabupaten_kota,
  kecamatan,
  kelurahan,
  kode_pos,
  alamat_detail,
  latitude,
  longitude,
  created_at,
  updated_at
FROM user_mgmt.master_lokasi WHERE false;
\copy _lok FROM 'csv/master_lokasi.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.master_lokasi (
  lokasi_id, provinsi, kabupaten_kota, kecamatan, kelurahan, kode_pos,
  alamat_detail, latitude, longitude, created_at, updated_at
)
SELECT * FROM _lok
ON CONFLICT (lokasi_id) DO NOTHING;
DROP TABLE _lok;

CREATE TEMP TABLE _plk AS SELECT
  pelaku_umkm_id,
  akun_id,
  nama_pelaku,
  nik,
  no_hp,
  email,
  alamat,
  status_aktif,
  is_deleted,
  deleted_at,
  archived_at,
  created_at,
  updated_at
FROM user_mgmt.master_pelakuumkm WHERE false;
\copy _plk FROM 'csv/master_pelakuumkm.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.master_pelakuumkm (
  pelaku_umkm_id, akun_id, nama_pelaku, nik, no_hp, email, alamat,
  status_aktif, is_deleted, deleted_at, archived_at, created_at, updated_at
)
SELECT * FROM _plk
ON CONFLICT (pelaku_umkm_id) DO NOTHING;
DROP TABLE _plk;

CREATE TEMP TABLE _umkm AS SELECT
  umkm_id,
  kode_umkm,
  pelaku_umkm_id,
  diverifikasi_oleh_admin_id,
  lokasi_id,
  jenis_umkm_id,
  skala_usaha_id,
  kategori_usaha_id,
  status_umkm_id,
  nama_umkm,
  nib,
  deskripsi_usaha,
  produk_utama,
  tahun_berdiri,
  nomor_whatsapp,
  email_bisnis,
  jam_operasional,
  media_sosial_marketplace,
  logo_url,
  foto_cover_url,
  status_verified,
  tanggal_terdaftar,
  is_deleted,
  deleted_at,
  archived_at,
  created_at,
  updated_at
FROM user_mgmt.master_umkm WHERE false;
\copy _umkm FROM 'csv/master_umkm.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.master_umkm (
  umkm_id, kode_umkm, pelaku_umkm_id, diverifikasi_oleh_admin_id, lokasi_id,
  jenis_umkm_id, skala_usaha_id, kategori_usaha_id, status_umkm_id,
  nama_umkm, nib, deskripsi_usaha, produk_utama, tahun_berdiri,
  nomor_whatsapp, email_bisnis, jam_operasional, media_sosial_marketplace,
  logo_url, foto_cover_url, status_verified, tanggal_terdaftar, is_deleted,
  deleted_at, archived_at, created_at, updated_at
)
SELECT * FROM _umkm
ON CONFLICT (umkm_id) DO NOTHING;
DROP TABLE _umkm;

CREATE TEMP TABLE _pdk AS SELECT
  produk_id,
  umkm_id,
  kategori_produk_id,
  nama_produk,
  deskripsi_produk,
  harga,
  stok_saat_ini,
  status_produk,
  legalitas_produk,
  is_deleted,
  deleted_at,
  archived_at,
  created_at,
  updated_at
FROM user_mgmt.master_produkumkm WHERE false;
\copy _pdk FROM 'csv/master_produkumkm.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.master_produkumkm (
  produk_id, umkm_id, kategori_produk_id, nama_produk, deskripsi_produk,
  harga, stok_saat_ini, status_produk, legalitas_produk, is_deleted,
  deleted_at, archived_at, created_at, updated_at
)
SELECT * FROM _pdk
ON CONFLICT (produk_id) DO NOTHING;
DROP TABLE _pdk;

CREATE TEMP TABLE _mtr AS SELECT
  mitra_id,
  kode_mitra,
  akun_id,
  diverifikasi_oleh_admin_id,
  lokasi_id,
  jenis_mitra_id,
  status_mitra_id,
  skala_kerjasama_id,
  nama_mitra,
  nama_badan_hukum,
  nib,
  npwp,
  nama_pic,
  jabatan_pic,
  kontak_pic,
  email_pic,
  alamat_mitra,
  wilayah_operasional,
  deskripsi_dukungan,
  logo_url,
  foto_cover_url,
  status_verified,
  is_deleted,
  deleted_at,
  archived_at,
  created_at,
  updated_at
FROM user_mgmt.master_mitra WHERE false;
\copy _mtr FROM 'csv/master_mitra.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.master_mitra (
  mitra_id, kode_mitra, akun_id, diverifikasi_oleh_admin_id, lokasi_id,
  jenis_mitra_id, status_mitra_id, skala_kerjasama_id, nama_mitra,
  nama_badan_hukum, nib, npwp, nama_pic, jabatan_pic, kontak_pic,
  email_pic, alamat_mitra, wilayah_operasional, deskripsi_dukungan,
  logo_url, foto_cover_url, status_verified, is_deleted, deleted_at,
  archived_at, created_at, updated_at
)
SELECT * FROM _mtr
ON CONFLICT (mitra_id) DO NOTHING;
DROP TABLE _mtr;

CREATE TEMP TABLE _mtb AS SELECT
  mitra_id,
  bidang_kemitraan_id,
  created_at
FROM user_mgmt.master_mitrabidangkemitraan WHERE false;
\copy _mtb FROM 'csv/master_mitrabidangkemitraan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.master_mitrabidangkemitraan (mitra_id, bidang_kemitraan_id, created_at)
SELECT * FROM _mtb
ON CONFLICT (mitra_id, bidang_kemitraan_id) DO NOTHING;
DROP TABLE _mtb;

CREATE TEMP TABLE _mduk AS SELECT
  mitra_id,
  bentuk_dukungan_id,
  created_at
FROM user_mgmt.master_mitrabentukdukungan WHERE false;
\copy _mduk FROM 'csv/master_mitrabentukdukungan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.master_mitrabentukdukungan (mitra_id, bentuk_dukungan_id, created_at)
SELECT * FROM _mduk
ON CONFLICT (mitra_id, bentuk_dukungan_id) DO NOTHING;
DROP TABLE _mduk;

-- =============================================================================
-- TRAINING MASTER TABLES
-- =============================================================================
CREATE TEMP TABLE _tprog AS SELECT
  pelatihan_id,
  kode_pelatihan,
  dibuat_oleh_admin_id,
  jenis_pelatihan_id,
  status_pelatihan_id,
  judul_pelatihan,
  deskripsi_pelatihan,
  mentor_nama,
  durasi_jam,
  total_modul,
  harga,
  akses_seumur_hidup,
  masa_akses_hari,
  rating_rata_rata,
  jumlah_alumni,
  thumbnail_url,
  syarat_ketentuan,
  tanggal_publish,
  is_deleted,
  deleted_at,
  archived_at,
  created_at,
  updated_at
FROM training.master_programpelatihan WHERE false;
\copy _tprog FROM 'csv/master_programpelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO training.master_programpelatihan (
  pelatihan_id, kode_pelatihan, dibuat_oleh_admin_id, jenis_pelatihan_id,
  status_pelatihan_id, judul_pelatihan, deskripsi_pelatihan, mentor_nama,
  durasi_jam, total_modul, harga, akses_seumur_hidup, masa_akses_hari,
  rating_rata_rata, jumlah_alumni, thumbnail_url, syarat_ketentuan,
  tanggal_publish, is_deleted, deleted_at, archived_at, created_at, updated_at
)
SELECT * FROM _tprog
ON CONFLICT (pelatihan_id) DO NOTHING;
DROP TABLE _tprog;

CREATE TEMP TABLE _tmod AS SELECT
  modul_id,
  pelatihan_id,
  urutan_modul,
  judul_modul,
  deskripsi_modul,
  durasi_menit,
  materi_url,
  is_preview,
  status_aktif,
  created_at
FROM training.master_modulpelatihan WHERE false;
\copy _tmod FROM 'csv/master_modulpelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO training.master_modulpelatihan (
  modul_id, pelatihan_id, urutan_modul, judul_modul, deskripsi_modul,
  durasi_menit, materi_url, is_preview, status_aktif, created_at
)
SELECT * FROM _tmod
ON CONFLICT (modul_id) DO NOTHING;
DROP TABLE _tmod;

CREATE TEMP TABLE _tass AS SELECT
  assignment_id,
  pelatihan_id,
  judul_assignment,
  deskripsi_assignment,
  instruksi_submission,
  due_days_after_enroll,
  status_aktif,
  created_at
FROM training.master_assignmentpelatihan WHERE false;
\copy _tass FROM 'csv/master_assignmentpelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO training.master_assignmentpelatihan (
  assignment_id, pelatihan_id, judul_assignment, deskripsi_assignment,
  instruksi_submission, due_days_after_enroll, status_aktif, created_at
)
SELECT * FROM _tass
ON CONFLICT (assignment_id) DO NOTHING;
DROP TABLE _tass;

-- =============================================================================
-- DOCUMENTS AND TRANSACTIONS
-- =============================================================================
CREATE TEMP TABLE _doc AS SELECT
  dokumen_id,
  jenis_dokumen_id,
  status_dokumen_id,
  uploader_akun_id,
  owner_type,
  owner_id,
  context_type,
  context_id,
  original_file_name,
  stored_file_name,
  file_extension,
  mime_type,
  file_size_bytes,
  bucket_name,
  object_key,
  storage_path,
  public_url,
  checksum_sha256,
  version_id,
  is_public,
  display_order,
  caption,
  uploaded_at,
  verified_at,
  expired_at,
  metadata_json
FROM document.transaksi_dokumenterunggah WHERE false;
\copy _doc FROM 'csv/transaksi_dokumenterunggah.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO document.transaksi_dokumenterunggah (
  dokumen_id, jenis_dokumen_id, status_dokumen_id, uploader_akun_id,
  owner_type, owner_id, context_type, context_id, original_file_name,
  stored_file_name, file_extension, mime_type, file_size_bytes, bucket_name,
  object_key, storage_path, public_url, checksum_sha256, version_id,
  is_public, display_order, caption, uploaded_at, verified_at, expired_at,
  metadata_json
)
SELECT * FROM _doc
ON CONFLICT (dokumen_id) DO NOTHING;
DROP TABLE _doc;

CREATE TEMP TABLE _reg AS SELECT
  akun_id,
  umkm_id,
  diverifikasi_oleh_admin_id,
  mitra_id,
  status_verifikasi_id,
  kode_registrasi,
  tanggal_submit,
  tanggal_review,
  tanggal_aktivasi,
  catatan_validasi,
  checklist_informasi_lengkap,
  created_at
FROM user_mgmt.transaksi_registrasipengguna WHERE false;
\copy _reg FROM 'csv/transaksi_registrasipengguna.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.transaksi_registrasipengguna (
  akun_id, umkm_id, diverifikasi_oleh_admin_id, mitra_id,
  status_verifikasi_id, kode_registrasi, tanggal_submit, tanggal_review,
  tanggal_aktivasi, catatan_validasi, checklist_informasi_lengkap, created_at
)
SELECT * FROM _reg
ON CONFLICT (akun_id) DO NOTHING;
DROP TABLE _reg;

CREATE TEMP TABLE _tpen AS SELECT
  pendaftaran_pelatihan_id,
  umkm_id,
  pelatihan_id,
  status_pendaftaran_pelatihan_id,
  tanggal_daftar,
  akses_mulai_at,
  akses_berakhir_at,
  terakhir_diakses_at,
  progress_persen,
  modul_selesai,
  total_modul_snapshot,
  tanggal_selesai
FROM training.transaksi_pendaftaranpelatihan WHERE false;
\copy _tpen FROM 'csv/transaksi_pendaftaranpelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO training.transaksi_pendaftaranpelatihan (
  pendaftaran_pelatihan_id, umkm_id, pelatihan_id,
  status_pendaftaran_pelatihan_id, tanggal_daftar, akses_mulai_at,
  akses_berakhir_at, terakhir_diakses_at, progress_persen, modul_selesai,
  total_modul_snapshot, tanggal_selesai
)
SELECT * FROM _tpen
ON CONFLICT (pendaftaran_pelatihan_id) DO NOTHING;
DROP TABLE _tpen;

CREATE TEMP TABLE _tsub AS SELECT
  pendaftaran_pelatihan_id,
  assignment_id,
  status_submission_id,
  dokumen_id,
  submission_link,
  submitted_at,
  reviewed_at
FROM training.transaksi_submissionassignment WHERE false;
\copy _tsub FROM 'csv/transaksi_submissionassignment.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO training.transaksi_submissionassignment (
  pendaftaran_pelatihan_id, assignment_id, status_submission_id, dokumen_id,
  submission_link, submitted_at, reviewed_at
)
SELECT * FROM _tsub
ON CONFLICT DO NOTHING;
DROP TABLE _tsub;

CREATE TEMP TABLE _tcert AS SELECT
  pendaftaran_pelatihan_id,
  status_sertifikat_id,
  dokumen_id,
  nomor_sertifikat,
  tanggal_pengajuan,
  tanggal_terbit,
  diverifikasi_oleh_admin_id,
  catatan_validasi
FROM training.transaksi_sertifikatpelatihan WHERE false;
\copy _tcert FROM 'csv/transaksi_sertifikatpelatihan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO training.transaksi_sertifikatpelatihan (
  pendaftaran_pelatihan_id, status_sertifikat_id, dokumen_id,
  nomor_sertifikat, tanggal_pengajuan, tanggal_terbit,
  diverifikasi_oleh_admin_id, catatan_validasi
)
SELECT * FROM _tcert
ON CONFLICT DO NOTHING;
DROP TABLE _tcert;

CREATE TEMP TABLE _tpks AS SELECT
  pengajuan_id,
  kode_pengajuan,
  umkm_id,
  mitra_id,
  pengaju_akun_id,
  penerima_akun_id,
  status_pengajuan_id,
  pesan_pengajuan,
  catatan_keputusan,
  dokumen_perjanjian_id,
  tanggal_pengajuan,
  tanggal_keputusan,
  tanggal_upload_dokumen,
  tanggal_mulai_kerjasama,
  tanggal_selesai_kerjasama,
  created_at,
  updated_at
FROM partnership.transaksi_pengajuankerjasama WHERE false;
\copy _tpks FROM 'csv/transaksi_pengajuankerjasama.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO partnership.transaksi_pengajuankerjasama (
  pengajuan_id, kode_pengajuan, umkm_id, mitra_id, pengaju_akun_id,
  penerima_akun_id, status_pengajuan_id, pesan_pengajuan, catatan_keputusan,
  dokumen_perjanjian_id, tanggal_pengajuan, tanggal_keputusan,
  tanggal_upload_dokumen, tanggal_mulai_kerjasama, tanggal_selesai_kerjasama,
  created_at, updated_at
)
SELECT * FROM _tpks
ON CONFLICT (pengajuan_id) DO NOTHING;
DROP TABLE _tpks;

-- =============================================================================
-- SALES, STOCK, AND MONITORING TRANSACTIONS
-- =============================================================================
CREATE TEMP TABLE _sales AS SELECT
  penjualan_id,
  umkm_id,
  tanggal_transaksi,
  nomor_transaksi,
  total_omzet,
  total_laba,
  total_item,
  catatan,
  status_transaksi,
  created_by_akun_id,
  created_at,
  updated_at
FROM dashboard.transaksi_penjualan WHERE false;
\copy _sales FROM 'csv/transaksi_penjualan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO dashboard.transaksi_penjualan (
  penjualan_id, umkm_id, tanggal_transaksi, nomor_transaksi,
  total_omzet, total_laba, total_item, catatan, status_transaksi,
  created_by_akun_id, created_at, updated_at
)
SELECT * FROM _sales
ON CONFLICT (penjualan_id) DO NOTHING;
DROP TABLE _sales;

CREATE TEMP TABLE _sales_item AS SELECT
  penjualan_item_id,
  penjualan_id,
  produk_id,
  nama_produk_snapshot,
  harga_satuan_snapshot,
  jumlah,
  created_at
FROM dashboard.transaksi_penjualan_item WHERE false;
\copy _sales_item FROM 'csv/transaksi_penjualan_item.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO dashboard.transaksi_penjualan_item (
  penjualan_item_id, penjualan_id, produk_id, nama_produk_snapshot,
  harga_satuan_snapshot, jumlah, created_at
)
SELECT * FROM _sales_item
ON CONFLICT (penjualan_item_id) DO NOTHING;
DROP TABLE _sales_item;

CREATE TEMP TABLE _stock AS SELECT
  stok_mutasi_id,
  produk_id,
  umkm_id,
  tipe_mutasi,
  jumlah_perubahan,
  stok_sebelum,
  stok_sesudah,
  referensi_tipe,
  referensi_id,
  catatan,
  created_by_akun_id,
  created_at
FROM user_mgmt.transaksi_stokproduk WHERE false;
\copy _stock FROM 'csv/transaksi_stokproduk.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO user_mgmt.transaksi_stokproduk (
  stok_mutasi_id, produk_id, umkm_id, tipe_mutasi, jumlah_perubahan,
  stok_sebelum, stok_sesudah, referensi_tipe, referensi_id, catatan,
  created_by_akun_id, created_at
)
SELECT * FROM _stock
ON CONFLICT (stok_mutasi_id) DO NOTHING;
DROP TABLE _stock;

CREATE TEMP TABLE _mon AS SELECT
  umkm_id,
  status_perkembangan_id,
  laba_harian,
  jumlah_produk,
  created_at
FROM dashboard.transaksi_monitoringperkembangan WHERE false;
\copy _mon FROM 'csv/transaksi_monitoringperkembangan.csv' WITH (FORMAT csv, HEADER true, NULL '');
INSERT INTO dashboard.transaksi_monitoringperkembangan (
  umkm_id, status_perkembangan_id, laba_harian, jumlah_produk, created_at
)
SELECT * FROM _mon
ON CONFLICT DO NOTHING;
DROP TABLE _mon;

-- =============================================================================
-- POST-LOAD SEQUENCE SYNC FOR TABLES WITH OPTIONAL GENERATED IDS
-- =============================================================================
-- Keep this safe even if tables do not use serial/bigserial ids.
DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT
      n.nspname AS schema_name,
      c.relname AS table_name,
      a.attname AS column_name,
      pg_get_serial_sequence(format('%I.%I', n.nspname, c.relname), a.attname) AS seq_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_attribute a ON a.attrelid = c.oid
    WHERE c.relkind = 'r'
      AND n.nspname IN ('auth', 'user_mgmt', 'training', 'document', 'partnership', 'dashboard')
      AND a.attnum > 0
      AND NOT a.attisdropped
  LOOP
    IF r.seq_name IS NOT NULL THEN
      EXECUTE format(
        'SELECT setval(%L, COALESCE((SELECT MAX(%I)::bigint FROM %I.%I), 1), true)',
        r.seq_name,
        r.column_name,
        r.schema_name,
        r.table_name
      );
    END IF;
  END LOOP;
END $$;

SELECT 'schema-first dummy CSV load completed' AS message;
