-- +goose Up

-- Auth service tables
-- ============================================================

CREATE TABLE auth.master_akunpengguna (
    akun_id VARCHAR(30) PRIMARY KEY,
    peran_id VARCHAR(30) NOT NULL REFERENCES ref.ref_peranpengguna(peran_id) ON UPDATE CASCADE,
    nama_lengkap VARCHAR(150) NOT NULL,
    email CITEXT NOT NULL,
    no_hp VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    status_aktif BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_master_akunpengguna_email UNIQUE (email),
    CONSTRAINT uq_master_akunpengguna_no_hp UNIQUE (no_hp),
    CONSTRAINT ck_master_akunpengguna_email CHECK (position('@' in email::text) > 1),
    CONSTRAINT ck_master_akunpengguna_timestamps CHECK (updated_at >= created_at)
);

CREATE TABLE auth.master_admin (
    admin_id VARCHAR(30) PRIMARY KEY,
    akun_id VARCHAR(30) NOT NULL UNIQUE REFERENCES auth.master_akunpengguna(akun_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    kode_admin VARCHAR(50) NOT NULL UNIQUE,
    is_active VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (is_active IN ('active', 'inactive')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Optional production auth/session tables. Not generated by the current CSV generator.
CREATE TABLE auth.transaksi_remember_tokens (
    remember_token_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    akun_id VARCHAR(30) NOT NULL REFERENCES auth.master_akunpengguna(akun_id) ON DELETE CASCADE ON UPDATE CASCADE,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    user_agent TEXT,
    ip_address INET,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_remember_tokens_expiry CHECK (expires_at > created_at)
);

CREATE TABLE auth.transaksi_kode_verifikasi (
    kode_verifikasi_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    akun_id VARCHAR(30) REFERENCES auth.master_akunpengguna(akun_id) ON DELETE CASCADE ON UPDATE CASCADE,
    email CITEXT NOT NULL,
    purpose VARCHAR(40) NOT NULL CHECK (purpose IN ('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'REGISTRATION')),
    code_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_kode_verifikasi_expiry CHECK (expires_at > created_at)
);

CREATE TABLE auth.transaksi_revoked_jwts (
    revoked_jwt_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    akun_id VARCHAR(30) REFERENCES auth.master_akunpengguna(akun_id) ON DELETE CASCADE ON UPDATE CASCADE,
    jwt_id VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
